config/routes.rb
Rails.application.routes.draw do

  #get 'password_resets/new'

  #get 'password_resets/edit'

  # Set Project Root Directory #
  root 'static_pages#home'

  # Set Project Static Page Directories #
  get '/help',      to: 'static_pages#help'
  get '/about',     to: 'static_pages#about'
  get '/contact',   to: 'static_pages#contact'

  # Set Project User Directories #
  get    '/signup',    to: 'users#new'
  post   '/signup',    to: 'users#create'
  get    '/login',     to: 'sessions#new'
  post   '/login',     to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'

  # Set Proejct Resources #
  resources :users
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" style="background-color: rgba(0,0,0,0.6)">
  <div class="container" style="background-color: transparent">
    <%= link_to image_tag('alien_head.png', width: '80px', height: '50px') + 'Cyb3r Board', root_path, id: 'logo' %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path, class: 'mnu_tag' %></li>
        <li><%= link_to "Help",   help_path, class: 'mnu_tag' %></li>
        <li><%= link_to "About",  about_path, class: 'mnu_tag' %></li>
        <% if logged_in? %>
          <li><% if current_user.admin? %><%= link_to "Users", users_path %><% end %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <p class="mnu_tag">Account <b class="caret"></b></p>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user, class: 'mnu_tag' %></li>
              <li><%= link_to "Settings", edit_user_path(current_user), class: 'mnu_tag' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete, class: 'mnu_tag' %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path, class: 'mnu_tag' %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Cinzel|Cormorant|Marcellus+SC|Orbitron|Righteous|Share+Tech+Mono&display=swap" rel="stylesheet">
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>